name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        work_dir: .
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: aviator-apk
        path: bin/*.apk
